import {test,expect} from '@playwright/test'
import pixelmatch from 'pixelmatch'
import {PNG} from 'pngjs'
import fs from 'node:fs'

const emotions=['neutral','happy','wink','surprised','sad','annoyed','sleepy','excited']
const expected={neutral:{mouth:0,gesture:0},happy:{mouth:1,gesture:0},wink:{mouth:1,gesture:0},surprised:{mouth:1,gesture:0},sad:{mouth:0,gesture:2},annoyed:{mouth:0,gesture:2},sleepy:{mouth:1,gesture:0},excited:{mouth:1,gesture:0}}
async function ready(page,emotion,reference=false){await page.goto(`/?qaEmotion=${emotion}${reference?'&qaReference=1':''}`);await page.locator('.rig-base').waitFor();await page.waitForFunction(()=>[...document.images].every(i=>i.complete));await page.addStyleTag({content:'*,*::before,*::after{animation:none!important;transition:none!important}.rig-root{transform:none!important}.reference-overlay{opacity:1!important;filter:none!important}'});await page.waitForTimeout(60)}
function comparePng(actualBuf,referenceBuf){const a=PNG.sync.read(actualBuf),r=PNG.sync.read(referenceBuf);expect(a.width).toBe(r.width);expect(a.height).toBe(r.height);const diff=new PNG({width:a.width,height:a.height});const pixels=pixelmatch(a.data,r.data,diff.data,a.width,a.height,{threshold:.1,includeAA:false});return{ratio:pixels/(a.width*a.height),diff:PNG.sync.write(diff)}}
async function state(page){return page.locator('[data-testid=rig-output]').evaluate(el=>({emotion:el.dataset.emotion,mouth:el.dataset.mouthLayers,gesture:el.dataset.gestureLayers,eyes:[...el.querySelectorAll('.eye-slot')].map(n=>n.getAttribute('style')),closed:[...el.querySelectorAll('.closed-eye-slot')].map(n=>n.getAttribute('style')),mouths:[...el.querySelectorAll('.mouth-slot')].map(n=>n.getAttribute('style')),brows:[...el.querySelectorAll('.brows path')].map(n=>n.getAttribute('d')),vector:el.querySelector('.rig-mouth-line')?.getAttribute('d')??null}))}
async function assertVisibleParts(page,emotion){const root=page.locator('[data-testid=rig-output]');await expect(root).toHaveAttribute('data-emotion',emotion);await expect(root).toHaveAttribute('data-mouth-layers',String(expected[emotion].mouth));await expect(root).toHaveAttribute('data-gesture-layers',String(expected[emotion].gesture));await expect(root.locator('.eye-slot')).toHaveCount(2);await expect(root.locator('.closed-eye-slot')).toHaveCount(2);const geom=await root.evaluate(el=>{const rr=el.getBoundingClientRect(),box=n=>{const r=n.getBoundingClientRect();return{x:r.left-rr.left+r.width/2,y:r.top-rr.top+r.height/2,w:r.width,h:r.height,opacity:Number(getComputedStyle(n).opacity)}};return{eyes:[...el.querySelectorAll('.eye-slot')].map(box),mouths:[...el.querySelectorAll('.mouth-slot')].map(box),gestures:[...el.querySelectorAll('.gesture-slot')].map(box)}});expect(geom.eyes).toHaveLength(2);expect(Math.abs(geom.eyes[0].x-125)).toBeLessThanOrEqual(4);expect(Math.abs(geom.eyes[1].x-233)).toBeLessThanOrEqual(4);for(const eye of geom.eyes){expect(eye.y).toBeGreaterThanOrEqual(160);expect(eye.y).toBeLessThanOrEqual(181);expect(eye.w).toBeGreaterThan(20);expect(eye.h).toBeGreaterThan(8);expect(eye.opacity).toBeGreaterThan(.95)}expect(geom.mouths).toHaveLength(expected[emotion].mouth);for(const mouth of geom.mouths){expect(Math.abs(mouth.x-179)).toBeLessThanOrEqual(5);expect(mouth.y).toBeGreaterThanOrEqual(212);expect(mouth.y).toBeLessThanOrEqual(232);expect(mouth.w).toBeGreaterThan(8);expect(mouth.h).toBeGreaterThan(6);expect(mouth.opacity).toBeGreaterThan(.99)}expect(geom.gestures).toHaveLength(expected[emotion].gesture);for(const g of geom.gestures){expect(g.x).toBeGreaterThan(100);expect(g.x).toBeLessThan(260);expect(g.y).toBeGreaterThan(235);expect(g.y).toBeLessThan(345)}}

test.describe('Jirai strict rendered QA',()=>{
 for(const emotion of emotions)test(`${emotion}: isolated endpoint stays within calibrated visual drift`,async({page},testInfo)=>{await ready(page,emotion,true);await assertVisibleParts(page,emotion);const overlay=page.locator('[data-testid=reference-overlay]'),rig=page.locator('[data-testid=rig-root]');await overlay.evaluate(el=>el.style.visibility='hidden');const actual=await rig.screenshot({animations:'disabled'});await rig.evaluate(el=>el.style.visibility='hidden');await overlay.evaluate(el=>{el.style.visibility='visible';el.style.opacity='1'});const reference=await overlay.screenshot({animations:'disabled'});await rig.evaluate(el=>el.style.visibility='visible');const{ratio,diff}=comparePng(actual,reference);const limit=.16;if(ratio>limit){const ap=testInfo.outputPath(`${emotion}-actual.png`),rp=testInfo.outputPath(`${emotion}-reference.png`),dp=testInfo.outputPath(`${emotion}-diff.png`);fs.writeFileSync(ap,actual);fs.writeFileSync(rp,reference);fs.writeFileSync(dp,diff);await testInfo.attach('actual',{path:ap,contentType:'image/png'});await testInfo.attach('reference',{path:rp,contentType:'image/png'});await testInfo.attach('diff',{path:dp,contentType:'image/png'})}expect(ratio,`${emotion} gross visual drift ${(ratio*100).toFixed(2)}%`).toBeLessThanOrEqual(limit)})
 for(const emotion of emotions)test(`${emotion}: endpoint has exact active parts and calibrated anchors`,async({page})=>{await ready(page,emotion);await assertVisibleParts(page,emotion)})
 test('transition history cannot contaminate final expression',async({page})=>{await ready(page,'neutral');for(const emotion of ['happy','sad','annoyed','wink','sleepy','excited','surprised','neutral']){await page.locator(`[data-emotion-button="${emotion}"]`).click();await page.waitForTimeout(560)}const afterHistory=await state(page);await ready(page,'neutral');const clean=await state(page);expect(afterHistory).toEqual(clean)})
})
