export type JiraiEmotion = 'neutral' | 'happy' | 'wink' | 'surprised' | 'sad' | 'annoyed' | 'sleepy' | 'excited'
export type EyeMode = 'open' | 'happy' | 'wink' | 'half' | 'closed' | 'sparkle'
export type Viseme = 'REST' | 'SMILE' | 'A' | 'E' | 'I' | 'O' | 'U'
export type VectorMouth = 'neutral' | 'smile' | 'frown' | 'annoyed'
export interface SpriteRect { x:number; y:number; w:number; h:number }
export interface ReferenceView { x:number; y:number; width:number; height:number }
export const JIRAI_EMOTIONS:JiraiEmotion[]=['neutral','happy','wink','surprised','sad','annoyed','sleepy','excited']
export const VISEMES:Viseme[]=['REST','SMILE','A','E','I','O','U']
const asset=(path:string)=>`${import.meta.env.BASE_URL}assets/jirai/rig-v3/${path}`
const referenceAsset=(emotion:JiraiEmotion)=>`${import.meta.env.BASE_URL}assets/jirai/expressions/${emotion}.png`
export const RIG_BASE_ASSET=asset('base/base_clean.png')
export const PARTS_ATLAS_ASSET=asset('parts_atlas.png')
export const PARTS_ATLAS_SIZE={width:256,height:331} as const
export const REFERENCE_ASSET:Record<JiraiEmotion,string>=Object.fromEntries(JIRAI_EMOTIONS.map(e=>[e,referenceAsset(e)])) as Record<JiraiEmotion,string>
export const REFERENCE_VIEW:Record<JiraiEmotion,ReferenceView>={
 neutral:{x:0,y:0,width:351,height:345},happy:{x:-11.227,y:-1.227,width:365.918,height:348.734},wink:{x:-5.277,y:-2.246,width:368.229,height:349.919},surprised:{x:2.761,y:-3.468,width:361.548,height:354.317},sad:{x:-.423,y:-.925,width:349.905,height:351.91},annoyed:{x:-11.78,y:-1.495,width:368.255,height:357.065},sleepy:{x:-4.218,y:-4.003,width:367.867,height:361.684},excited:{x:-.849,y:-5.199,width:365.394,height:364.35}
}
const R=(x:number,y:number,w:number,h:number):SpriteRect=>({x,y,w,h})
export const SPRITE={closedL:R(4,4,48,14),closedR:R(56,4,48,14),halfL:R(108,4,49,34),halfR:R(161,4,45,34),happyL:R(4,42,50,27),happyR:R(58,42,50,27),openL:R(112,42,52,55),openR:R(168,42,52,55),sparkleL:R(4,101,54,51),sparkleR:R(62,101,54,51),winkR:R(120,101,40,31),mouthA:R(164,101,43,35),mouthE:R(4,156,46,29),mouthI:R(54,156,42,32),mouthO:R(100,156,23,32),mouthREST:R(127,156,38,10),mouthSMILE:R(169,156,42,13),mouthU:R(215,156,18,25),annoyedL:R(4,192,69,43),annoyedR:R(77,192,68,47),sadL:R(149,192,59,63),sadR:R(4,259,63,68)} as const
interface EyeAssetPair{left:SpriteRect;right:SpriteRect}
export const EYE_ASSET:Record<EyeMode,EyeAssetPair>={open:{left:SPRITE.openL,right:SPRITE.openR},happy:{left:SPRITE.happyL,right:SPRITE.happyR},wink:{left:SPRITE.openL,right:SPRITE.winkR},half:{left:SPRITE.halfL,right:SPRITE.halfR},closed:{left:SPRITE.closedL,right:SPRITE.closedR},sparkle:{left:SPRITE.sparkleL,right:SPRITE.sparkleR}}
export const VISEME_RECT:Record<Viseme,SpriteRect>={REST:SPRITE.mouthREST,SMILE:SPRITE.mouthSMILE,A:SPRITE.mouthA,E:SPRITE.mouthE,I:SPRITE.mouthI,O:SPRITE.mouthO,U:SPRITE.mouthU}
interface BrowPose{y:number;tilt:number;arch:number;opacity:number}
interface Pose{eyes:EyeMode;eyeX:number;eyeY:number;leftEyeRotation:number;rightEyeRotation:number;brow:BrowPose;mouth:{kind:'vector';value:VectorMouth}|{kind:'sprite';value:Viseme;transitionLine:VectorMouth};rootY:number;rootRotation:number;gesture?:'sad'|'annoyed';mouthX:number;mouthY:number}
const POSE:Record<JiraiEmotion,Pose>={
 neutral:{eyes:'open',eyeX:0,eyeY:0,leftEyeRotation:0,rightEyeRotation:0,brow:{y:136,tilt:0,arch:4,opacity:1},mouth:{kind:'vector',value:'neutral'},rootY:0,rootRotation:0,mouthX:179,mouthY:221},
 happy:{eyes:'happy',eyeX:0,eyeY:1,leftEyeRotation:0,rightEyeRotation:0,brow:{y:136,tilt:-2,arch:4,opacity:.18},mouth:{kind:'sprite',value:'A',transitionLine:'smile'},rootY:0,rootRotation:0,mouthX:179,mouthY:220},
 wink:{eyes:'wink',eyeX:0,eyeY:0,leftEyeRotation:0,rightEyeRotation:0,brow:{y:136,tilt:1,arch:4,opacity:.7},mouth:{kind:'sprite',value:'A',transitionLine:'smile'},rootY:0,rootRotation:-.12,mouthX:179,mouthY:220},
 surprised:{eyes:'open',eyeX:0,eyeY:-2,leftEyeRotation:0,rightEyeRotation:0,brow:{y:130,tilt:0,arch:5,opacity:1},mouth:{kind:'sprite',value:'O',transitionLine:'neutral'},rootY:0,rootRotation:0,mouthX:179,mouthY:221},
 sad:{eyes:'sparkle',eyeX:0,eyeY:2,leftEyeRotation:0,rightEyeRotation:0,brow:{y:134,tilt:-11,arch:2,opacity:1},mouth:{kind:'vector',value:'frown'},rootY:0,rootRotation:0,mouthX:179,mouthY:223,gesture:'sad'},
 annoyed:{eyes:'half',eyeX:0,eyeY:5,leftEyeRotation:0,rightEyeRotation:0,brow:{y:137,tilt:10,arch:1,opacity:1},mouth:{kind:'vector',value:'annoyed'},rootY:0,rootRotation:0,mouthX:180,mouthY:222,gesture:'annoyed'},
 sleepy:{eyes:'closed',eyeX:0,eyeY:5,leftEyeRotation:0,rightEyeRotation:0,brow:{y:140,tilt:0,arch:3,opacity:.7},mouth:{kind:'sprite',value:'U',transitionLine:'neutral'},rootY:0,rootRotation:0,mouthX:179,mouthY:221},
 excited:{eyes:'open',eyeX:0,eyeY:-1,leftEyeRotation:0,rightEyeRotation:0,brow:{y:132,tilt:-2,arch:5,opacity:1},mouth:{kind:'sprite',value:'E',transitionLine:'smile'},rootY:0,rootRotation:0,mouthX:179,mouthY:221}
}
export interface EyeFrame{rect:SpriteRect;closedRect:SpriteRect;x:number;y:number;rotation:number;reveal:number;closedOpacity:number}
export interface MouthSpriteLayer{rect:SpriteRect;reveal:number;x:number;y:number}
export interface GestureLayer{rect:SpriteRect;x:number;y:number;offsetY:number}
interface MouthRenderState{path?:string;visible:boolean;sprites:MouthSpriteLayer[]}
export interface JiraiFrame{baseSrc:string;atlasSrc:string;referenceSrc:string;referenceView:ReferenceView;emotion:JiraiEmotion;transitionProgress:number;rootY:number;rootRotation:number;eyes:[EyeFrame,EyeFrame];browLeft:string;browRight:string;browOpacity:number;mouthVectorPath?:string;mouthVectorVisible:boolean;mouthSprites:MouthSpriteLayer[];gestures:GestureLayer[];statusLabel:string}
export interface JiraiInput{t:number;fromEmotion:JiraiEmotion;toEmotion:JiraiEmotion;emotionProgress:number;speaking:boolean;fromViseme:Viseme;toViseme:Viseme;visemeProgress:number;talkLevel:number}
const LEFT_EYE_X=125,RIGHT_EYE_X=233,EYE_Y=168
const clamp=(v:number,min=0,max=1)=>Math.max(min,Math.min(max,v)),lerp=(a:number,b:number,t:number)=>a+(b-a)*t
const smoothstep=(a:number,b:number,x:number)=>{const t=clamp((x-a)/(b-a));return t*t*(3-2*t)}
const ease=(p:number)=>{p=clamp(p);return p<.5?4*p*p*p:1-Math.pow(-2*p+2,3)/2}
function idleBlink(t:number,mode:EyeMode){if(mode==='closed'||mode==='happy')return 0;const c=(t+.37)%4.35;if(c>.18)return 0;const p=c/.18;return clamp(p<.46?p/.46:(1-p)/.54)}
function transitionClosure(p:number){if(p<=0||p>=1)return 0;return Math.pow(Math.sin(Math.PI*p),6)}
function browPath(cx:number,y:number,tilt:number,arch:number,side:-1|1){const half=17,slope=Math.tan(tilt*Math.PI/180)*half,y0=y+(side===-1?-slope:slope),y1=y+(side===-1?slope:-slope);return `M ${(cx-half).toFixed(2)} ${y0.toFixed(2)} Q ${cx.toFixed(2)} ${(y-arch).toFixed(2)} ${(cx+half).toFixed(2)} ${y1.toFixed(2)}`}
type Point=[number,number];type MouthControl=[Point,Point,Point,Point,Point,Point,Point,Point,Point,Point]
const VECTOR_MOUTH:Record<VectorMouth,MouthControl>={neutral:[[166,219],[168,223],[172,225],[176,220],[178,218],[180,218],[182,220],[186,225],[190,223],[192,219]],smile:[[165,218],[168,222],[172,225],[176,227],[178,228],[180,228],[182,227],[186,225],[190,222],[193,218]],frown:[[169,224],[171,220],[174,218],[177,221],[179,219],[181,218],[183,221],[186,218],[190,220],[192,224]],annoyed:[[170,222],[173,219],[177,218],[181,220],[184,221],[187,222],[190,221],[190,219],[189,216],[191,214]]}
function translateMouth(points:MouthControl,dx:number,dy:number):MouthControl{return points.map(([x,y])=>[x+dx,y+dy] as Point) as MouthControl}
function interpolateMouth(a:VectorMouth,b:VectorMouth,p:number,x:number,y:number){const A=VECTOR_MOUTH[a],B=VECTOR_MOUTH[b],P=A.map((pt,i)=>[lerp(pt[0],B[i][0],p),lerp(pt[1],B[i][1],p)] as Point) as MouthControl;const base=translateMouth(P,x-179,y-221);return `M ${base[0][0].toFixed(2)} ${base[0][1].toFixed(2)} C ${base[1][0].toFixed(2)} ${base[1][1].toFixed(2)} ${base[2][0].toFixed(2)} ${base[2][1].toFixed(2)} ${base[3][0].toFixed(2)} ${base[3][1].toFixed(2)} C ${base[4][0].toFixed(2)} ${base[4][1].toFixed(2)} ${base[5][0].toFixed(2)} ${base[5][1].toFixed(2)} ${base[6][0].toFixed(2)} ${base[6][1].toFixed(2)} C ${base[7][0].toFixed(2)} ${base[7][1].toFixed(2)} ${base[8][0].toFixed(2)} ${base[8][1].toFixed(2)} ${base[9][0].toFixed(2)} ${base[9][1].toFixed(2)}`}
const sprite=(v:Viseme,reveal:number,x:number,y:number):MouthSpriteLayer=>({rect:VISEME_RECT[v],reveal:clamp(reveal),x,y})
function emotionMouth(from:Pose,to:Pose,p:number):MouthRenderState{const q=ease(p),mx=lerp(from.mouthX,to.mouthX,q),my=lerp(from.mouthY,to.mouthY,q);if(from.mouth.kind==='vector'&&to.mouth.kind==='vector')return{path:interpolateMouth(from.mouth.value,to.mouth.value,q,mx,my),visible:true,sprites:[]};if(from.mouth.kind==='vector'&&to.mouth.kind==='sprite'){const reveal=smoothstep(.58,1,q);return{path:interpolateMouth(from.mouth.value,to.mouth.transitionLine,clamp(q/.68),mx,my),visible:reveal<.28,sprites:[sprite(to.mouth.value,reveal,mx,my)]}};if(from.mouth.kind==='sprite'&&to.mouth.kind==='vector'){const close=1-smoothstep(0,.43,q);return{path:interpolateMouth(from.mouth.transitionLine,to.mouth.value,smoothstep(.34,1,q),mx,my),visible:q>.34,sprites:[sprite(from.mouth.value,close,mx,my)]}};const a=from.mouth as Extract<Pose['mouth'],{kind:'sprite'}>,b=to.mouth as Extract<Pose['mouth'],{kind:'sprite'}>;return{path:interpolateMouth(a.transitionLine,b.transitionLine,smoothstep(.38,.62,q),mx,my),visible:q>=.38&&q<=.62,sprites:[sprite(a.value,1-smoothstep(0,.43,q),mx,my),sprite(b.value,smoothstep(.57,1,q),mx,my)]}}
function speakingMouth(from:Viseme,to:Viseme,p:number,talk:number):MouthRenderState{const a:Viseme=talk<.1?'REST':from,b:Viseme=talk<.1?'REST':to;if(a===b||p>=1)return{visible:false,sprites:[sprite(b,1,179,221)]};const q=ease(p),bridge=smoothstep(.3,.48,q)*(1-smoothstep(.52,.7,q));return{visible:false,sprites:[sprite(a,1-smoothstep(0,.46,q),179,221),sprite('REST',bridge,179,221),sprite(b,smoothstep(.54,1,q),179,221)]}}
function gestureFor(kind:'sad'|'annoyed',offsetY:number):GestureLayer[]{return kind==='sad'?[{rect:SPRITE.sadL,x:143.5,y:274.5,offsetY},{rect:SPRITE.sadR,x:219.5,y:276,offsetY}]:[{rect:SPRITE.annoyedL,x:146.5,y:317.5,offsetY},{rect:SPRITE.annoyedR,x:217,y:315.5,offsetY}]}
export function sampleJirai(input:JiraiInput):JiraiFrame{const p=clamp(input.emotionProgress),q=ease(p),from=POSE[input.fromEmotion],to=POSE[input.toEmotion],mode=p<.5?from.eyes:to.eyes,eyeAsset=EYE_ASSET[mode],closure=Math.max(transitionClosure(p),idleBlink(input.t,input.toEmotion===input.fromEmotion?to.eyes:mode)),reveal=1-closure,closedOpacity=smoothstep(.62,.94,closure),eyeX=lerp(from.eyeX,to.eyeX,q),eyeY=lerp(from.eyeY,to.eyeY,q),browY=lerp(from.brow.y,to.brow.y,q),browTilt=lerp(from.brow.tilt,to.brow.tilt,q),browArch=lerp(from.brow.arch,to.brow.arch,q),browOpacity=lerp(from.brow.opacity,to.brow.opacity,q),breath=Math.sin(input.t*(input.toEmotion==='sleepy'?1.1:1.48))*.18,rootY=breath,rootRotation=lerp(from.rootRotation,to.rootRotation,q),mouth:MouthRenderState=input.speaking?speakingMouth(input.fromViseme,input.toViseme,clamp(input.visemeProgress),clamp(input.talkLevel)):emotionMouth(from,to,p),gestures:GestureLayer[]=[];if(from.gesture===to.gesture&&to.gesture)gestures.push(...gestureFor(to.gesture,0));else{if(from.gesture&&q<.5)gestures.push(...gestureFor(from.gesture,smoothstep(0,.5,q)*12));if(to.gesture&&q>=.5)gestures.push(...gestureFor(to.gesture,(1-smoothstep(.5,1,q))*12))}return{baseSrc:RIG_BASE_ASSET,atlasSrc:PARTS_ATLAS_ASSET,referenceSrc:REFERENCE_ASSET[input.toEmotion],referenceView:REFERENCE_VIEW[input.toEmotion],emotion:input.toEmotion,transitionProgress:p,rootY,rootRotation,eyes:[{rect:eyeAsset.left,closedRect:SPRITE.closedL,x:LEFT_EYE_X+eyeX,y:EYE_Y+eyeY,rotation:lerp(from.leftEyeRotation,to.leftEyeRotation,q),reveal,closedOpacity},{rect:eyeAsset.right,closedRect:SPRITE.closedR,x:RIGHT_EYE_X+eyeX,y:EYE_Y+eyeY,rotation:lerp(from.rightEyeRotation,to.rightEyeRotation,q),reveal,closedOpacity}],browLeft:browPath(125,browY,browTilt,browArch,-1),browRight:browPath(233,browY,browTilt,browArch,1),browOpacity,mouthVectorPath:mouth.path,mouthVectorVisible:mouth.visible,mouthSprites:mouth.sprites,gestures,statusLabel:`${input.toEmotion.toUpperCase()} · CUTOUT RIG V3.1${input.speaking?` · ${input.toViseme}`:''}`}}
export const RIG_V3_RULES={rasterMorph:false,emotionTransitionMs:430,eyeSwapAtProgress:.5,eyeSwapRequiresClosure:.9,visemeGateMs:90} as const
